  # Vocabulary definition of ical
  RDFA_ICAL = {
    :name => :ical,
    :fullname => "",

    :description => "",

    :url => "",

    :namespace => "http://www.w3.org/2002/12/cal/ical#",

    :classes => {
        "Value_RECUR"=>"",
        "Value_CAL-ADDRESS"=>"",
        "List_of_Float"=>"",
        "Vjournal"=>"Provide a grouping of component properties that describe a journal entry.",
        "Valarm"=>"Provide a grouping of component properties that define an alarm.",
        "Value_PERIOD"=>"",
        "Value_DURATION"=>"",
        "Vtimezone"=>"Provide a grouping of component properties that defines a time zone.",
        "Vtodo"=>"Provide a grouping of calendar properties that describe a to-do.",
        "Value_DATE"=>"",
        "Value_DATE-TIME"=>"",
        "Vevent"=>"Provide a grouping of component properties that describe an event.",
        "Vfreebusy"=>"Provide a grouping of component properties that describe either a request for free/busy time, describe a response to a request for free/busy time or describe a published set of busy time.",
        "DomainOf_rrule"=>""
    },

    :properties => {
        "duration"=>"The property specifies a positive duration of time.",
        "comment"=>"This property specifies non-processing information intended to provide a comment to the calendar user.",
        "sequence"=>"This property defines the revision sequence number of the calendar component within a sequence of revisions.",
        "location"=>"The property defines the intended venue for the activity defined by a calendar component.",
        "lastModified"=>"The property specifies the date and time that the information associated with the calendar component was last revised in the calendar store. Note: This is analogous to the modification date and time for a file in the file system.",
        "rdate"=>"This property defines the list of date/times for a recurrence set.",
        "recurrenceId"=>"This property is used in conjunction with the \\",
        "tzoffsetto"=>"This property specifies the offset which is in use in this time zone observance.",
        "completed"=>"This property defines the date and time that a to-do was actually completed.",
        "class"=>"This property defines the access classification for a calendar component.",
        "rrule"=>"This property defines a rule or repeating pattern for recurring events, to-dos, or time zone definitions.",
        "tzid"=>"This property specifies the text value that uniquely identifies the \\",
        "method"=>"This property defines the iCalendar object method associated with the calendar object.",
        "trigger"=>"This property specifies when an alarm will trigger.",
        "action"=>"This property defines the action to be invoked when an alarm is triggered.",
        "url"=>"This property defines a Uniform Resource Locator (URL) associated with the iCalendar object.",
        "organizer"=>"The property defines the organizer for a calendar component.",
        "contact"=>"The property is used to represent contact information or alternately a reference to contact information associated with the calendar component.",
        "dtend"=>"This property specifies the date and time that a calendar component ends.",
        "priority"=>"The property defines the relative priority for a calendar component.",
        "requestStatus"=>"This property defines the status code returned for a scheduling request.",
        "repeat"=>"This property defines the number of time the alarm should be repeated, after the initial trigger.",
        "exdate"=>"This property defines the list of date/time exceptions for a recurring calendar component.",
        "uid"=>"This property defines the persistent, globally unique identifier for the calendar component.",
        "tzoffsetfrom"=>"This property specifies the offset which is in use prior to this time zone observance.",
        "dtstart"=>"This property specifies when the calendar component begins.",
        "resources"=>"This property defines the equipment or resources anticipated for an activity specified by a calendar entity..",
        "dtstamp"=>"The property indicates the date/time that the instance of the iCalendar object was created.",
        "exrule"=>"This property defines a rule or repeating pattern for an exception to a recurrence set.",
        "geo"=>"This property specifies information related to the global position for the activity specified by a calendar component.",
        "version"=>"This property specifies the identifier corresponding to the highest version number or the minimum and maximum range of the iCalendar specification that is required in order to interpret the iCalendar object.",
        "attach"=>"The property provides the capability to associate a document object with a calendar component.",
        "relatedTo"=>"The property is used to represent a relationship or reference between one calendar component and another.",
        "attendee"=>"The property defines an \\",
        "tzname"=>"This property specifies the customary designation for a time zone description.",
        "transp"=>"This property defines whether an event is transparent or not to busy time searches.",
        "summary"=>"This property defines a short summary or subject for the calendar component.",
        "description"=>"This property provides a more complete description of the calendar component, than that provided by the \\",
        "categories"=>"This property defines the categories for a calendar component.",
        "calscale"=>"This property defines the calendar scale used for the calendar information specified in the iCalendar object.",
        "tzurl"=>"The TZURL provides a means for a VTIMEZONE component to point to a network location that can be used to retrieve an up-to- date version of itself.",
        "freebusy"=>"The property defines one or more free or busy time intervals.",
        "due"=>"This property defines the date and time that a to-do is expected to be completed.",
        "status"=>"This property defines the overall status or confirmation for the calendar component.",
        "prodid"=>"This property specifies the identifier for the product that created the iCalendar object.",
        "X-"=>"This class of property provides a framework for defining non-standard properties.",
        "created"=>"This property specifies the date and time that the calendar information was created by the calendar user agent in the calendar store. Note: This is analogous to the creation date and time for a file in the file system.",
        "percentComplete"=>"This property is used by an assignee or delegatee of a to-do to convey the percent completion of a to-do to the Organizer."}
    }

# kate: space-indent on; indent-width 2; replace-tabs on; mixed-indent off;
